#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

SCRIPT_DIRECTORY=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPOSITORY_DIRECTORY=$(cd -- "$SCRIPT_DIRECTORY/.." && pwd)
PUBLIC_SITE_HOST="public-demo.africantechnologyforum.org"
BACKEND_CMS_HOST="cms-demo.africantechnologyforum.org"
PUBLIC_SITE_ORIGIN="https://${PUBLIC_SITE_HOST}"
BACKEND_CMS_ORIGIN="https://${BACKEND_CMS_HOST}"

banner "Fetched-CMS Demo Rehearsal"

stage "Choose an isolated Demo Rehearsal"
say "This wizard refuses to store demo secrets in the repository or its root .env file."
if [[ "$ENV_FILE" == ".env" ]]; then
  warn "Set ENV_FILE to a path outside the repository, then run the wizard again."
  exit 1
fi
if [[ "$ENV_FILE" != /* ]]; then
  warn "Set ENV_FILE to an absolute path outside the repository."
  exit 1
fi
case "$ENV_FILE" in
  "$REPOSITORY_DIRECTORY"/*)
    warn "The Demo Rehearsal environment file must stay outside the repository."
    exit 1
    ;;
esac
mkdir -p -- "$(dirname -- "$ENV_FILE")"
COMPOSE_PROJECT_NAME="atf-backend-cms-demo"
POSTGRES_DB="atf_cms_demo"
POSTGRES_USER="payload_demo"
PAYLOAD_BIND_ADDRESS="127.0.0.1"
PAYLOAD_PORT="3002"
write_env COMPOSE_PROJECT_NAME "$COMPOSE_PROJECT_NAME"
write_env POSTGRES_DB "$POSTGRES_DB"
write_env POSTGRES_USER "$POSTGRES_USER"
write_env PAYLOAD_BIND_ADDRESS "$PAYLOAD_BIND_ADDRESS"
write_env PAYLOAD_PORT "$PAYLOAD_PORT"
note "The project name and host port cannot collide with the Production Launch."

stage "Create the Backend CMS secrets"
say "Use new values. Do not paste a production password or Payload secret."
ask_secret POSTGRES_PASSWORD "Enter a URL-safe PostgreSQL password with at least 24 characters:"
if [[ ! "$POSTGRES_PASSWORD" =~ ^[A-Za-z0-9._~-]{24,}$ ]]; then
  warn "Use at least 24 URL-safe characters: letters, digits, dot, underscore, tilde, or hyphen."
  exit 1
fi
ask_secret PAYLOAD_SECRET "Enter a URL-safe Payload secret with at least 32 characters:"
if [[ ! "$PAYLOAD_SECRET" =~ ^[A-Za-z0-9._~-]{32,}$ ]]; then
  warn "Use at least 32 URL-safe characters: letters, digits, dot, underscore, tilde, or hyphen."
  exit 1
fi
DATABASE_URI="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
PAYLOAD_ALLOWED_ORIGINS="${BACKEND_CMS_ORIGIN},${PUBLIC_SITE_ORIGIN}"
write_env POSTGRES_PASSWORD "$POSTGRES_PASSWORD"
write_env DATABASE_URI "$DATABASE_URI"
write_env PAYLOAD_SECRET "$PAYLOAD_SECRET"
write_env PAYLOAD_PUBLIC_SERVER_URL "$BACKEND_CMS_ORIGIN"
write_env PAYLOAD_PUBLIC_SITE_ORIGIN "$PUBLIC_SITE_ORIGIN"
write_env PAYLOAD_ALLOWED_ORIGINS "$PAYLOAD_ALLOWED_ORIGINS"
chmod 600 "$ENV_FILE"
note "The wizard stored the demo configuration in $ENV_FILE with mode 600."

stage "Build and start the Demo Backend CMS"
say "Docker Compose will use only the atf-backend-cms-demo project and the selected environment file."
if confirm "Build the checked-out release and start the demo project now?"; then
  COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" \
    make -C "$REPOSITORY_DIRECTORY/backend-cms" build ENV=prod ENV_FILE="$ENV_FILE"
  COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" \
    make -C "$REPOSITORY_DIRECTORY/backend-cms" start ENV=prod ENV_FILE="$ENV_FILE"
  curl --fail --show-error --silent \
    "http://${PAYLOAD_BIND_ADDRESS}:${PAYLOAD_PORT}/api/health"
  printf '\n'
  note "The local demo health endpoint returned successfully."
else
  SKIPPED+=("build and start the atf-backend-cms-demo Compose project")
fi

stage "Configure the Demo Public Site"
say "Create a separate Vercel project from this repository. Do not reuse the Production Launch project."
open_url "https://vercel.com/dashboard"
step "Import this repository and set the project root to a single dot."
step "Set the build command to npm run build and the output directory to dist."
step "Set VITE_BACKEND_CMS_ORIGIN to $BACKEND_CMS_ORIGIN."
step "Set VITE_HOMEPAGE_ONLY_MODE to false."
step "Deploy the checked-out commit, then add $PUBLIC_SITE_HOST as the custom domain."
note "vercel.json supplies the SPA rewrite and the host-specific X-Robots-Tag header."
pause "Press Enter after Vercel shows the deployment and custom domain as ready."

stage "Publish the two HTTPS origins"
say "Point the Backend CMS hostname at the demo reverse proxy and keep PostgreSQL private."
ask REVERSE_PROXY_DASHBOARD_URL "Enter the reverse-proxy dashboard URL, or leave it blank to open it yourself:"
if [[ -n "$REVERSE_PROXY_DASHBOARD_URL" ]]; then
  open_url "$REVERSE_PROXY_DASHBOARD_URL"
fi
step "Create a proxy host for $BACKEND_CMS_HOST."
step "Forward it to 127.0.0.1 on port $PAYLOAD_PORT, or to the equivalent private host address."
step "Enable WebSocket support, obtain a valid TLS certificate, and force HTTPS."
step "Use the DNS records shown by Vercel for $PUBLIC_SITE_HOST."
pause "Press Enter after DNS and both HTTPS certificates are ready."
curl --fail --show-error --silent "$BACKEND_CMS_ORIGIN/api/health"
printf '\n'
curl --fail --show-error --silent --output /dev/null \
  "$PUBLIC_SITE_ORIGIN/preview/news/release-proof"
DEMO_HEADERS=$(curl --fail --show-error --silent --head "$PUBLIC_SITE_ORIGIN/")
if ! grep -Eiq '^x-robots-tag:[[:space:]]*noindex,[[:space:]]*nofollow' <<< "$DEMO_HEADERS"; then
  warn "The Demo Rehearsal response did not contain X-Robots-Tag: noindex, nofollow."
  exit 1
fi
PRODUCTION_HEADERS=$(curl --fail --show-error --silent --head \
  "https://africantechnologyforum.org/")
if grep -Eiq '^x-robots-tag:[[:space:]]*noindex,[[:space:]]*nofollow' <<< "$PRODUCTION_HEADERS"; then
  warn "The Production Launch unexpectedly declares itself non-indexable."
  exit 1
fi
note "Both demo origins respond over HTTPS, direct preview navigation loads, and the indexing headers are isolated."

stage "Prove the editorial and failure paths"
open_url "$BACKEND_CMS_ORIGIN/admin"
step "Create the first Admin and a separate Editor. Use demo-only credentials."
step "As the Editor, create a draft News Article with an image and non-empty alt text."
step "Use Live Preview. Change the title, body, and image, and confirm that populated Media renders before publication."
step "Publish the article and inspect the homepage, /news, /news/<slug>, and /publications in a private window."
step "Save a newer draft, restore an earlier version, and confirm that neither change reaches the Visitor until publication."
step "As the Admin, change the published slug and confirm that the Previous News Slug replaces browser history with the current URL."
step "In browser developer tools, confirm that the login response cookie contains Secure=true."
step "Block the hero-image request and confirm that Image unavailable replaces only the image."
pause "Press Enter after the Admin, Editor, Visitor, Live Preview, slug, cookie, and Media checks pass."
if confirm "Run the outage and persistence checks against the disposable demo project?"; then
  COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" \
    make -C "$REPOSITORY_DIRECTORY/backend-cms" stop ENV=prod ENV_FILE="$ENV_FILE"
  step "Reload each news surface. Confirm the five-second limit, no automatic retry, visible Retry action, shared layout, and no snapshot."
  pause "Press Enter after the outage behavior passes."
  COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" \
    make -C "$REPOSITORY_DIRECTORY/backend-cms" start ENV=prod ENV_FILE="$ENV_FILE"
  step "Select Retry and confirm that published news returns."
  pause "Press Enter after the retry succeeds."
  COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" \
    make -C "$REPOSITORY_DIRECTORY/backend-cms" down ENV=prod ENV_FILE="$ENV_FILE"
  COMPOSE_PROJECT_NAME="$COMPOSE_PROJECT_NAME" \
    make -C "$REPOSITORY_DIRECTORY/backend-cms" start ENV=prod ENV_FILE="$ENV_FILE"
  step "Confirm that the demo users, News Article, PostgreSQL data, and Media still exist."
  pause "Press Enter after the persistence check passes."
else
  SKIPPED+=("demo outage, retry, and persistence checks")
fi
say "Append the checked-out commit, URLs, command results, and observations to the open release-proof ticket."
warn "Do not record secrets, passwords, session cookies, or DATABASE_URI."

finish
