/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as WhereWeWorkRouteImport } from './routes/where-we-work'
import { Route as WhatWeDoRouteImport } from './routes/what-we-do'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ConsultingRouteImport } from './routes/consulting'
import { Route as ChaptersRouteImport } from './routes/chapters'
import { Route as ChallengeRouteImport } from './routes/challenge'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewsSlugRouteImport } from './routes/news_.$slug'
import { Route as CountriesCountryRouteImport } from './routes/countries.$country'

const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const WhereWeWorkRoute = WhereWeWorkRouteImport.update({
  id: '/where-we-work',
  path: '/where-we-work',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatWeDoRoute = WhatWeDoRouteImport.update({
  id: '/what-we-do',
  path: '/what-we-do',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultingRoute = ConsultingRouteImport.update({
  id: '/consulting',
  path: '/consulting',
  getParentRoute: () => rootRouteImport,
} as any)
const ChaptersRoute = ChaptersRouteImport.update({
  id: '/chapters',
  path: '/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeRoute = ChallengeRouteImport.update({
  id: '/challenge',
  path: '/challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsSlugRoute = NewsSlugRouteImport.update({
  id: '/news_/$slug',
  path: '/news/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCountryRoute = CountriesCountryRouteImport.update({
  id: '/countries/$country',
  path: '/countries/$country',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/challenge': typeof ChallengeRoute
  '/chapters': typeof ChaptersRoute
  '/consulting': typeof ConsultingRoute
  '/library': typeof LibraryRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/where-we-work': typeof WhereWeWorkRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/countries/$country': typeof CountriesCountryRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/challenge': typeof ChallengeRoute
  '/chapters': typeof ChaptersRoute
  '/consulting': typeof ConsultingRoute
  '/library': typeof LibraryRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/where-we-work': typeof WhereWeWorkRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/countries/$country': typeof CountriesCountryRoute
  '/news/$slug': typeof NewsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/articles': typeof ArticlesRoute
  '/challenge': typeof ChallengeRoute
  '/chapters': typeof ChaptersRoute
  '/consulting': typeof ConsultingRoute
  '/library': typeof LibraryRoute
  '/news': typeof NewsRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/publications': typeof PublicationsRoute
  '/research': typeof ResearchRoute
  '/team': typeof TeamRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/what-we-do': typeof WhatWeDoRoute
  '/where-we-work': typeof WhereWeWorkRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/countries/$country': typeof CountriesCountryRoute
  '/news_/$slug': typeof NewsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/articles'
    | '/challenge'
    | '/chapters'
    | '/consulting'
    | '/library'
    | '/news'
    | '/privacy-policy'
    | '/publications'
    | '/research'
    | '/team'
    | '/terms-of-service'
    | '/what-we-do'
    | '/where-we-work'
    | '/who-we-are'
    | '/countries/$country'
    | '/news/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/articles'
    | '/challenge'
    | '/chapters'
    | '/consulting'
    | '/library'
    | '/news'
    | '/privacy-policy'
    | '/publications'
    | '/research'
    | '/team'
    | '/terms-of-service'
    | '/what-we-do'
    | '/where-we-work'
    | '/who-we-are'
    | '/countries/$country'
    | '/news/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/articles'
    | '/challenge'
    | '/chapters'
    | '/consulting'
    | '/library'
    | '/news'
    | '/privacy-policy'
    | '/publications'
    | '/research'
    | '/team'
    | '/terms-of-service'
    | '/what-we-do'
    | '/where-we-work'
    | '/who-we-are'
    | '/countries/$country'
    | '/news_/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArticlesRoute: typeof ArticlesRoute
  ChallengeRoute: typeof ChallengeRoute
  ChaptersRoute: typeof ChaptersRoute
  ConsultingRoute: typeof ConsultingRoute
  LibraryRoute: typeof LibraryRoute
  NewsRoute: typeof NewsRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  PublicationsRoute: typeof PublicationsRoute
  ResearchRoute: typeof ResearchRoute
  TeamRoute: typeof TeamRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WhatWeDoRoute: typeof WhatWeDoRoute
  WhereWeWorkRoute: typeof WhereWeWorkRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
  CountriesCountryRoute: typeof CountriesCountryRoute
  NewsSlugRoute: typeof NewsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/where-we-work': {
      id: '/where-we-work'
      path: '/where-we-work'
      fullPath: '/where-we-work'
      preLoaderRoute: typeof WhereWeWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-we-do': {
      id: '/what-we-do'
      path: '/what-we-do'
      fullPath: '/what-we-do'
      preLoaderRoute: typeof WhatWeDoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulting': {
      id: '/consulting'
      path: '/consulting'
      fullPath: '/consulting'
      preLoaderRoute: typeof ConsultingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chapters': {
      id: '/chapters'
      path: '/chapters'
      fullPath: '/chapters'
      preLoaderRoute: typeof ChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge': {
      id: '/challenge'
      path: '/challenge'
      fullPath: '/challenge'
      preLoaderRoute: typeof ChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news_/$slug': {
      id: '/news_/$slug'
      path: '/news/$slug'
      fullPath: '/news/$slug'
      preLoaderRoute: typeof NewsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$country': {
      id: '/countries/$country'
      path: '/countries/$country'
      fullPath: '/countries/$country'
      preLoaderRoute: typeof CountriesCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArticlesRoute: ArticlesRoute,
  ChallengeRoute: ChallengeRoute,
  ChaptersRoute: ChaptersRoute,
  ConsultingRoute: ConsultingRoute,
  LibraryRoute: LibraryRoute,
  NewsRoute: NewsRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  PublicationsRoute: PublicationsRoute,
  ResearchRoute: ResearchRoute,
  TeamRoute: TeamRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WhatWeDoRoute: WhatWeDoRoute,
  WhereWeWorkRoute: WhereWeWorkRoute,
  WhoWeAreRoute: WhoWeAreRoute,
  CountriesCountryRoute: CountriesCountryRoute,
  NewsSlugRoute: NewsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
